version: "3.8"

services:
  forume-api:
    container_name: api-prod
    restart: always
    build:
      context: ./go/api
      dockerfile: Dockerfile
    volumes:
      - ./go/api/db:/go/src/app/db
    ports:
      - 8081:8081

  forume-client:
    container_name: client-prod
    restart: always
    build:
      context: ./react
      dockerfile: Dockerfile.prod
    volumes:
      - "./react:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - forume-api
